config/routes.rb
Rails.application.routes.draw do


  scope :module => 'buttercms' do
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/blog/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/blog/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    get '/blog/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap

    get '/blog(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/blog/:slug' => 'posts#show', :as => :buttercms_post
  end


  resources :practices, except: [:destroy]

  get 'auth/:provider/callback', to: 'users#calendar_auth'
  post 'stripe/create', to: 'stripe_accounts#create'
  post 'stripe/update', to: 'stripe_accounts#update', as: "stripe_update"

  mount StripeEvent::Engine => '/stripe'

  get 'blog', to: 'posts#index'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'days/check'
  get 'days/check_end'

  post 'sync_cal', to: "appointments#calendar_sync"

  get 'invitation/new'

  get 'invitation/create'

   get 'conversations/index'

   get 'conversations/create'

  get 'comments/index'

  get 'comments/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'marketplaces/index'

  get 'invoices/index'

  resources :appointment_settings

  get 'resources/index'

  get 'practices/booking_complete/:appointment_id', to: 'practices#booking_complete', as: "booking_complete"
  get '/messages', to: 'messages#index'
  get '/messages/new', to: "messages#new"
  resources :days
  resources :subscriptions
  resources :bank_accounts
  get 'conversations/reply', to: 'conversations#reply'
  resources :conversations, :defaults => { :format => :json } do
    resources :messages
  end
  get 'sessions/new'

  get 'connection', to: 'reminders#new'

  root 'static_pages#home'
  get 'privacy', to: 'static_pages#privacy'
  resources :users do
    resources :comments
    resources :profiles
    resources :todo_lists do
      resources :todo_items
    end
    member do
      get :patients, :doctors
    end
  end
  resources :appointments do
    resources :comments
  end
  resources :user_complaints
  get '/relationships/reconfirm', to: 'relationships#reconfirm_relationship'
  get '/relationships/confirm/', to: 'relationships#confirm_relationship'
  get '/relationships/add_patient/', to: 'relationships#confirm'
  get '/relationships/add_patient/(:relationship_token)', to: 'relationships#confirm'
  post '/relationships/patient_decision/', to: 'relationships#patient_decision'
  get '/days/check', to: 'days#check'
  get '/days/check_end', to: 'days#check_end'

  get '/users/check_billing/:doctor_id', to: 'users#check_billing', defaults: {format: :json}

  resource :calendar, only: [:show]
  resource :dashboard, only: [:show]
  resource :invoice, only: [:index]
  resources :relationships,       only: [:new,:create, :destroy, :update]
  get  '/signup/(:invitation_token)',  to: 'users#new'
  get  '/search/users',  to: 'users#search'
  post '/signup',  to: 'users#create'
  resources :leads, has_many: :inquiries
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :invitations, only: [:new, :create]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'documents/' => 'documents#index'
  get 'documents/new' => 'documents#new', as: :new_document
  get 'documents/:id' => 'documents#show', as: :document
  post 'documents/' => 'documents#create'
  get 'documents/:id/edit' => 'documents#edit', as: :edit_document
  patch 'documents/:id' => 'documents#update'
  delete 'documents/:id' => 'documents#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_user
      redirect_to current_user
    else
      @content = ButterCMS::Content.fetch([
        :homepage_headline,
        :homepage_paragraph,
        :homepage_cta_text,
        :standard_features,
        :enterprise_features
      ]).data

      @lead = Lead.new
      @inquiry = @lead.inquiries.build
    end
  end

  def privacy
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_pricing.html.erb
<section id="pricing">
  <div class="pricing-headline">
    <p>14 Day Free Trial.  No Credit Card Required.</p>
  </div>
  <div class="pricing-tabs">

    <ul class="pricing-nav">
      <li class="current-pricing pricing-tab"><a href="javascript:void(0)">Standard</a></li>
      <li class="pricing-tab"><a href="javascript:void(0)">Enterprise</a></li>
    </ul>

  </div>

  <div class="pricing-tables">
    <div id="Standard" class="pricing-table current-table">
      <div class="half">
        <h3 class="ticket"><span class="dollar">$</span>39<span>/month</span></h3>
      </div>
      <div class="half"><h5>Included Features:</h5>
        <ul class="feature-list">
          <li><i class="icon-ok"></i>Patient Notes</li>
          <li><i class="icon-ok"></i>Scheduling</li>
          <li><i class="icon-ok"></i>Communication</li>
          <li><i class="icon-ok"></i>Billing</li>
        </ul>
        <%= link_to 'Start your trial', new_user_path, class: "btn btn-pricing" %>
      </div>
      <div class="row"></div>
    </div>

    <div id="Enterprise" class="pricing-table">
      <div class="half">
        <h3 class="ticket"><span class="dollar">$</span>129<span>/mo</span></h3>
      </div>
      <div class="half">
        <h5>Included Features:</h5>
        <ul class="feature-list">
          <li><i class="icon-ok"></i>All standard features</li>
          <li><i class="icon-ok"></i>Phone Support</li>
          <li><i class="icon-ok"></i>Personal Assistance</li>
          <li><i class="icon-ok"></i>Customization</li>
        </ul>
        <%= link_to 'Start your trial', new_user_path, class: "btn btn-pricing" %>
      </div>
      <div class="row"></div>
    </div>
  </div>
</section>

app/views/static_pages/_testimonials.html.erb
<!-- Testimonial/quote section -->
<section id="quote">
	<div class="row">
		<div class="twelve columns">
		<h3><i class="icon-hangouts"></i>What our customers say ?</h3>

			<div class="flexslider">
				<ul class="slides">

					<li data-thumb="<%= image_url "demo/quote/1.png" %>">
						<p>Donec elementum mollis magna id aliquet. Etiam eleifend urna eget sem sagittis feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras facilisis felis placerat quam sodales sit amet tempor leo scelerisque.</p>
						<div class="sign">John Doe /<span> Some profession</span></div>
					</li>

					<li data-thumb="<%= image_url "demo/quote/2.png" %>">
						<p>Donec elementum mollis magna id aliquet. Etiam eleifend urna eget sem sagittis feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras facilisis felis placerat quam sodales sit amet tempor leo scelerisque.</p>
						<div class="sign">John Doe /<span> Some profession</span></div>

					</li>

					<li data-thumb="<%= image_url "demo/quote/3.png" %>">
						<p>Donec elementum mollis magna id aliquet. Etiam eleifend urna eget sem sagittis feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras facilisis felis placerat quam sodales sit amet tempor leo scelerisque.</p>
						<div class="sign">John Doe /<span> Some profession</span></div>

					</li>

					<li data-thumb="<%= image_url "demo/quote/4.png" %>">
						<p>Donec elementum mollis magna id aliquet. Etiam eleifend urna eget sem sagittis feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras facilisis felis placerat quam sodales sit amet tempor leo scelerisque.</p>
						<div class="sign">John Doe /<span> Some profession</span></div>
					</li>

					<li data-thumb="<%= image_url "demo/quote/5.png" %>">
						<p>Donec elementum mollis magna id aliquet. Etiam eleifend urna eget sem sagittis feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras facilisis felis placerat quam sodales sit amet tempor leo scelerisque.</p>
						<div class="sign">John Doe /<span> Some profession</span></div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<!-- Testimonial/quote section -->

app/views/static_pages/_video.html.erb
<!-- Video section -->
<section id="review">
	<div class="row">
		<div class="twelve columns">
			<div class="eleven columns centered">
				<h3><i class="icon-circleplayempty"></i>Check this video to know more about this app</h3>
				<div class="video">
					<iframe height="281" src="http://player.vimeo.com/video/71175857?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff&amp;autoplay=0" width="500"></iframe>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Video section -->

app/views/static_pages/checkout.html.erb
<% provide(:title, "Checkout") %>
<h1>StaticPages#checkout</h1>
<p>Find me in app/views/static_pages/checkout.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!-- Header section -->
<header>
	<div class="top-wrap">
		<div class="row">
			<div class="twelve columns">

				<!-- Logo content -->
				<div class="four columns logo">
					<%= image_tag "logo.png", height: 60, width: 180 %>
				</div>

				<!-- Navmenu content -->
				<div class="eight columns">
					<ul class="top-nav">
						<li class="current scroll"><a href="#top">Home</a></li>
						<li class="scroll"><a href="#team">Mission</a></li>
						<li class="scroll"><a href="#features">Features</a></li>
						<li class="scroll"><a href="#pricing">Plans</a></li>
						<li class="scroll"><%= link_to "Blog", blog_path, class: " offpage" %></li>

						<li class="blank"><%= link_to "Login", login_path, class: "btn offpage" %></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</header>
<!-- Header section -->

<!-- Slider section -->
<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
<section id="top">
	<div class="row">
		<div class="twelve columns">
			<div class="space90"></div>

			<!-- Slider content -->
			<div class="six columns">
				<div id="main-slider" class="flexslider">
					<ul class="slides">
						<li><%= image_tag "grey_comp.png" %></li>
						<!--<li><<%= image_tag "demo/slide/2.png" %></li>-->
					</ul>
				</div>
			</div>

			<!-- Content right -->
			<div class="six columns top-info">
				<h3><%= @content.homepage_headline %></h3>
				<%= @content.homepage_paragraph.html_safe %>
				<div class="space50"></div>
				<%= link_to raw("<em>#{@content.homepage_cta_text}</em>"), new_user_path, class: "btn" %>

			</div>
		</div>
	</div>
</section>
<!-- Slider section -->

<!-- Features/services section -->
<section id="team">
	<div class="row">
		<div class="twelve columns">
			<h3 class="purple">Mission</h3>
			<div class="row">
				<div class="six columns"><h5>We Started With A Problem</h5><p>We built PatientNotes because the most efficient ways to manage a practice and communicate with your patients are constantly evolving, and so should you. If your software isn’t efficient for both you and your patients, your growth is limited. We  designed a platform that bridges the gap between efficient practice management and seamless communication.   </p></div>

				<div class="six columns"><h5>Run Your Practice On Your Own Terms</h5><p>PatientNotes is a solution that will save you time and change the way you interact with your patients. Losing or trucking around notes, and asking patients for their credit card at the end of a session are things of the past.  Receive emails with daily updates on your practice and upcoming sessions, check in with your patients in between appointments, and automate all of your billing. Our goal is to improve the experience for patients by saving you time and making your job easier.</p>  </div>

			</div>


<!-- Social content -->
		<!--	<div class="six columns team-content">

				<h4>Daniel Meek</h4>
				<h5>Founder</h5>



			</div>

			<div class="six columns team-content">

				<h4>Colleen Breslin</h4>
				<h5>Founder</h5> -->

				<!-- Social content -->

			</div>
		</div>
	</div>
</section>
<div class="row">
<hr>
</div>
<section id="features">
	<div class="row">
		<div class="twelve columns">
			<div class="four columns features-content">
				<div class="ico" style="color:#999;"><i class="icon-inkpen"></i></div>
				<div class="features-info">
					<h4 class="purple">Patient Notes</h4>
					<p>
						Whether it's diagnosis or session notes, PatientNotes is your comprehensive, secure solution.</p>
				</div>
			</div>

			<div class="four columns features-content">
				<div class="ico" style="color:#999;"><i class="icon-invoice"></i></div>
				<div class="features-info">
					<h4 class="purple">Electronic Billing</h4>
					<p>Submit claims (EDI), accept credit cards, send invoices, and store patient billing information.</p>
				</div>
			</div>

			<div class="four columns features-content">
				<div class="ico" style="color:#999;"><i class="icon-mobile"></i></div>
				<div class="features-info">
					<h4 class="purple">Seamless Communication</h4>
					<p>Automated text, email, and telephone communication to facilitate best patient care.</p>
				</div>
			</div>
		</div>

		<div class="twelve columns">
			<div class="four columns features-content">
				<div class="ico" style="color:#999;"><i class="icon-calendarthree"></i></div>
				<div class="features-info">
					<h4 class="purple">Scheduling</h4>
					<p>Manage your appointments, personal schedule, and tasks all in one place!  Allow your patients to schedule online and receive automatic appointment reminders.</p>
				</div>
			</div>

			<div class="four columns features-content">
				<div class="ico" style="color:#999;"><i class="icon-lock"></i></div>
				<div class="features-info">
					<h4 class="purple">Security & compliance</h4>
					<p>HIPAA, Insurance, and PCI Compliant, so whether it's your personal information, your patient's notes or billing information, you can be confident it's secure.</p>
				</div>
			</div>

			<div class="four columns features-content">
				<div class="ico" style="color:#999;"><i class="icon-phonebookalt"></i></div>
				<div class="features-info">
					<h4 class="purple">Patient Portal</h4>
					<p>Allow your patients to schedule appointments and update billing and insurance information.  Customizable permission controls allow you to limit which patients are able to schedule.</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Features/services section -->
<section id="pricing">
  <div class="pricing-headline">
    <p>14 Day Free Trial.  No Credit Card Required.</p>
  </div>
  <div class="pricing-tabs">

    <ul class="pricing-nav">
      <li class="current-pricing pricing-tab"><a href="javascript:void(0)">Standard</a></li>
      <li class="pricing-tab"><a href="javascript:void(0)">Enterprise</a></li>
    </ul>

  </div>

  <div class="pricing-tables">
    <div id="Standard" class="pricing-table current-table">
      <div class="half">
        <h3 class="ticket"><span class="dollar">$</span>39<span>/month</span></h3>
      </div>
      <div class="half"><h5>Included Features:</h5>
        <ul class="feature-list">
        	<% @content.standard_features.each do |f| %>
          <li><i class="icon-ok"></i><%= f.name %></li>
          <% end %>
        </ul>
        <%= link_to 'Start your trial', new_user_path, class: "btn btn-pricing" %>
      </div>
      <div class="row"></div>
    </div>

    <div id="Enterprise" class="pricing-table">
      <div class="half">
        <h3 class="ticket"><span class="dollar">$</span>129<span>/mo</span></h3>
      </div>
      <div class="half">
        <h5>Included Features:</h5>
        <ul class="feature-list">
        	<% @content.enterprise_features.each do |f| %>
          <li><i class="icon-ok"></i><%= f.name %></li>
          <% end %>
        </ul>
        <%= link_to 'Start your trial', new_user_path, class: "btn btn-pricing" %>
      </div>
      <div class="row"></div>
    </div>
  </div>
</section>
<% render 'static_pages/video' %>

<!-- Team section -->

<!-- Team section -->

<% render "static_pages/testimonials" %>

<!-- Contact section -->
<%= render "leads/basic_form", lead: @lead, inquiry: @inquiry %>
<!-- Contact section -->

<!-- Footer section -->
<footer class="footer">
	<div class="row">
		<div class="twelve columns footer-inner">
			<p>&copy; 2016. Patient Notes. All Rights Reserved.</p>
		</div>
	</div>
</footer>
<div class="container">
<%= debug(params) if Rails.env.development? %>
</div>
<!-- Footer section -->
<!-- <script type="text/javascript">

(function(h,o,t,j,a,r){
		 h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
		 h._hjSettings={hjid:391457,hjsv:5};
		 a=o.getElementsByTagName('head')[0];
		 r=o.createElement('script');r.async=1;
		 r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
		 a.appendChild(r);
 })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
 console.log('hotJar');

 window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("2402286356");
			console.log('heap');

</script> -->

app/views/static_pages/privacy.html.slim
|We take privacy seriously