config/routes.rb
Rails.application.routes.draw do


  scope :module => 'buttercms' do
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/blog/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/blog/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    get '/blog/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap

    get '/blog(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/blog/:slug' => 'posts#show', :as => :buttercms_post
  end


  resources :practices, except: [:destroy]

  get 'auth/:provider/callback', to: 'users#calendar_auth'
  post 'stripe/create', to: 'stripe_accounts#create'
  post 'stripe/update', to: 'stripe_accounts#update', as: "stripe_update"

  mount StripeEvent::Engine => '/stripe'

  get 'blog', to: 'posts#index'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'days/check'
  get 'days/check_end'

  post 'sync_cal', to: "appointments#calendar_sync"

  get 'invitation/new'

  get 'invitation/create'

   get 'conversations/index'

   get 'conversations/create'

  get 'comments/index'

  get 'comments/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'marketplaces/index'

  get 'invoices/index'

  resources :appointment_settings

  get 'resources/index'

  get 'practices/booking_complete/:appointment_id', to: 'practices#booking_complete', as: "booking_complete"
  get '/messages', to: 'messages#index'
  get '/messages/new', to: "messages#new"
  resources :days
  resources :subscriptions
  resources :bank_accounts
  get 'conversations/reply', to: 'conversations#reply'
  resources :conversations, :defaults => { :format => :json } do
    resources :messages
  end
  get 'sessions/new'

  get 'connection', to: 'reminders#new'

  root 'static_pages#home'
  get 'privacy', to: 'static_pages#privacy'
  resources :users do
    resources :comments
    resources :profiles
    resources :todo_lists do
      resources :todo_items
    end
    member do
      get :patients, :doctors
    end
  end
  resources :appointments do
    resources :comments
  end
  resources :user_complaints
  get '/relationships/reconfirm', to: 'relationships#reconfirm_relationship'
  get '/relationships/confirm/', to: 'relationships#confirm_relationship'
  get '/relationships/add_patient/', to: 'relationships#confirm'
  get '/relationships/add_patient/(:relationship_token)', to: 'relationships#confirm'
  post '/relationships/patient_decision/', to: 'relationships#patient_decision'
  get '/days/check', to: 'days#check'
  get '/days/check_end', to: 'days#check_end'

  get '/users/check_billing/:doctor_id', to: 'users#check_billing', defaults: {format: :json}

  resource :calendar, only: [:show]
  resource :dashboard, only: [:show]
  resource :invoice, only: [:index]
  resources :relationships,       only: [:new,:create, :destroy, :update]
  get  '/signup/(:invitation_token)',  to: 'users#new'
  get  '/search/users',  to: 'users#search'
  post '/signup',  to: 'users#create'
  resources :leads, has_many: :inquiries
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :invitations, only: [:new, :create]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'documents/' => 'documents#index'
  get 'documents/new' => 'documents#new', as: :new_document
  get 'documents/:id' => 'documents#show', as: :document
  post 'documents/' => 'documents#create'
  get 'documents/:id/edit' => 'documents#edit', as: :edit_document
  patch 'documents/:id' => 'documents#update'
  delete 'documents/:id' => 'documents#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :logged_in_user
  def index
    messages = []
    receipts = []
    conversations = current_user.mailbox.conversations
    conversations.each do |conversation|
      conversation.receipts_for(current_user).each do |receipt|
        unless receipt.message.sender_id == current_user.id
          new_message = receipt.message
          messages << receipt.message
          receipts << receipt
        end
      end
    end
    grouped_messages = messages.group_by{|m| m.created_at.strftime("%a, %b %-d")}
    # @messages = messages.collect do |message|
    #     {:subject => "sample subject"}
    # end
    @grouped = grouped_messages
    @receipts = receipts
    email_json = {}
    email_json["emails"] = []
    email_array = []
    grouped_messages.each do |key, array|
      day_group = {}
      day_group["group"] = key
      day_group["list"] = []
      array.each do |message|
        info = {}
        info["id"]= message.id,
        info["conversation_id"] = message.conversation_id,
        info["subject"]= message.subject,
        info["to"]= [User.find(message.sender_id).full_name],
        info["body"]= message.body,
        info["time"]= message.created_at.strftime('%l%p'),
        info["datetime"]= "#{message.created_at.strftime('%a-%d')} at #{message.created_at.strftime('%l%p')}",
        info["from"]= User.find(Mailboxer::Conversation.find(message.conversation_id).receipts.where(mailbox_type: "inbox").first.receiver_id).full_name,
        info["dp"]= "assets/img/profiles/avatar.jpg",
        info["dpRetina"]= "assets/img/profiles/avatar2x.jpg"
        day_group["list"] << info
      end
      email_json["emails"] << day_group
    end
    render json: email_json
  end

  def create
    recipient = User.find(params[:user_id])
    current_user.send_message(recipient, params[:body], params[:subject])
    flash[:success] = "You message has been sent."
    redirect_to messages_path
  end

  def new
    @recipients = (current_user.doctors + current_user.patients).uniq
    respond_to do |format|
      format.js {}
    end
  end

  def reply
    @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper

  def get_recipient_name conversation
    if conversation.sender_id == current_user
      recipient = User.find(conversation.recipient_id)
      "#{recipient.first_name} #{recipient.last_name}"
    else
      recipient = User.find(conversation.sender_id)
      "#{recipient.first_name} #{recipient.last_name}"
    end
  end
end

app/views/conversations/_new.html.slim
.email-composer.container-fluid
  .row
    .col-sm-12.no-padding
      .wysiwyg5-wrapper.email-toolbar-wrapper
        = form_tag conversations_path, method: :post do
          .form-group-attached
            .row.clearfix
              .col-sm-12
                .form-group.form-group-default
                  label To:
                  =select_tag :user_id, content_tag(:option,'Pick a recipient...',:value=>"")+options_from_collection_for_select(@recipients, :id, :name), class:"form-control tagsinput", data: {role: "tagsinput"}
              
            .form-group.form-group-default
              label Subject
              =text_field_tag :subject,nil, class:"form-control",placeholder: "Subject"
          
          wysiwyg5-wrapper.email-body-wrapper
            =text_area_tag :body,nil, class:"wysiwyg5 email-body", style:"height:350px", placeholder:"Enter your message here..."
          .row.p-b-20
            .col-sm-11
            =submit_tag "Send", class:"button btn btn-complete btn-cons m-l-10 new-message"

app/views/conversations/_reply_form.html.slim
=form_tag conversation_messages_path(@conversation), method: :post do
  .wysiwyg5-wrapper.b-a.b-grey.m-t-30
    =text_area_tag :body, nil, class:"email-reply", placeholder:"Reply"
  =submit_tag "Reply", class:"btn btn-lg pull-right btn-primary" 

app/views/conversations/create.html.erb
<h1>Conversations#create</h1>
<p>Find me in app/views/conversations/create.html.erb</p>

app/views/conversations/new.js.erb
$(".new-email").html("<%= j render('conversations/new') %>").fadeIn(1500);
if ($.Pages.isVisibleSm() || $.Pages.isVisibleXs()) {
    $('.split-list').toggleClass('slideLeft');
}
$('.new-email').show();
$('.actions, .no-result').hide();
$('.email-content-wrapper').hide();

// $('.email-composer').on('click', '.new-message', function() {
//   alert('before');
//   $.ajax({type: "POST",url: "/conversations/new",data:{sender: $('#conversation_sender_id').val(), recipient: $('#conversation_recipient_id').val()}});
//   alert('after');
// });

setTimeout(function() {
    $('.wysiwyg5').wysihtml5();
}, 500);

app/views/conversations/reply.js.erb
$('.reply_section').html('<%=j render "conversations/reply_form" %>');